// api/_azpg.js against a REAL PostgreSQL, with db/schema.sql applied.
//
// WHY a live database and not a mock: the translator's whole job is to make
// Postgres answer exactly what PostgREST would have answered (timestamps as
// ISO strings, numerics as numbers, embeds as objects/arrays, defaults applied
// when a column is omitted). None of that can be asserted against a fake —
// the bugs it guards against were all "the SQL looked right" bugs.
//
// Runs only when a Postgres is reachable at AZPG_TEST_URL (default: the local
// bp_test database). Otherwise every test is SKIPPED, never failed — CI and
// other developers' machines may have no Postgres at all.
//
// Isolation: a throw-away schema `azpg_t_<hex>` is created, schema.sql is
// applied inside it, the translator is pointed at it through the URL's
// `options=-c search_path=…` (columnsOf() keys on current_schema()), and the
// schema is dropped at the end. The server's public schema is never touched.
import { test, before, after } from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const TEST_URL = process.env.AZPG_TEST_URL || "postgres://bp_test:bp_test@127.0.0.1:5432/bp_test";
const SCHEMA = `azpg_t_${crypto.randomBytes(4).toString("hex")}`;
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// Probe first, synchronously for the test runner (top-level await), so the
// skip reason is known before any test is registered.
let pg = null, admin = null, unavailable = "";
try {
  pg = (await import("pg")).default;
  admin = new pg.Pool({ connectionString: TEST_URL, connectionTimeoutMillis: 1500, max: 1 });
  await admin.query("select 1");
} catch (e) {
  unavailable = `PostgreSQL not reachable at ${TEST_URL.replace(/\/\/[^@]*@/, "//…@")} (${e.code || e.message}) — set AZPG_TEST_URL`;
  try { await admin?.end(); } catch {}
  admin = null;
}
const it = (name, fn) => test(name, { skip: unavailable || false }, fn);

let azpg = null;   // the module under test, imported only after env is set
const rest = (p, o) => azpg.azpgRest(p, o);
const post = (table, body, prefer) => rest(table, { method: "POST", body, prefer });
const uuidRe = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const isoRe = /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(\.\d+)?\+00:00$/;
const uniq = (p) => `${p}-${crypto.randomBytes(3).toString("hex")}`;

// Shared fixtures: one organization and one user; each test adds its own rows
// (keyed by unique values) so tests stay independent of each other's order.
let ORG = null, USER = null;

before(async () => {
  if (unavailable) return;
  const c = await admin.connect();
  try {
    await c.query(`create schema ${SCHEMA}`);
    await c.query(`set search_path to ${SCHEMA}`);
    // schema.sql is written for the Supabase SQL editor: one multi-statement
    // string (do $$ blocks, policies, an extension). pg runs it as a simple
    // query, which is exactly how the editor does it.
    await c.query(fs.readFileSync(path.join(ROOT, "db", "schema.sql"), "utf8"));
  } finally { c.release(); }

  process.env.AZURE_PG_URL = `${TEST_URL}${TEST_URL.includes("?") ? "&" : "?"}options=-c%20search_path%3D${SCHEMA}`;
  process.env.AZURE_PG_SSL = "0";          // local server has no TLS
  process.env.AZURE_PG_POOL_MAX = "2";
  azpg = await import(`../api/_azpg.js?t=${Date.now()}`);
  azpg.azpgForgetColumns();

  [ORG] = await post("organizations", { name_ar: "منشأة الاختبار", name_en: "Test Org", city: "الرياض" });
  [USER] = await post("users", { email: uniq("owner") + "@test.local", full_name: "Owner", locale: "ar" });
});

after(async () => {
  if (unavailable) return;
  try { if (azpg) await azpg.azpgClose(); } catch {}
  try { await admin.query(`drop schema ${SCHEMA} cascade`); } finally { await admin.end(); }
});

// ------------------------------------------------------------------ INSERT --
it("POST applies DB defaults for omitted columns — even across rows with different column sets", async () => {
  // Regression: an earlier version sent an explicit NULL for every column any
  // row in the batch mentioned, which overrides `default now()` and breaks
  // `not null` on id/created_at. Rows must be grouped by their own columns.
  const rows = await post("organizations", [
    { name_ar: "أ" },
    { name_ar: "ب", city: "جدة", profile_completeness: 40 },
  ]);
  assert.equal(rows.length, 2);
  const a = rows.find((r) => r.name_ar === "أ"), b = rows.find((r) => r.name_ar === "ب");
  for (const r of [a, b]) {
    assert.match(r.id, uuidRe, "id generated by gen_random_uuid()");
    assert.match(r.created_at, isoRe, "created_at from default now()");
    assert.match(r.updated_at, isoRe);
  }
  assert.equal(a.city, null);
  assert.equal(a.profile_completeness, 0, "int default applied, as a number");
  assert.equal(b.city, "جدة");
  assert.equal(b.profile_completeness, 40);
  assert.equal(await post("organizations", [], "return=minimal"), null, "empty batch is a no-op");
});

// ----------------------------------------------------------------- SESSION --
it("the exact session lookup from api/_db.js: nested users object, expiry compared as time", async () => {
  const live = uniq("live"), dead = uniq("dead");
  await post("user_sessions", [
    { user_id: USER.id, organization_id: ORG.id, token_hash: live, expires_at: new Date(Date.now() + 3600e3).toISOString() },
    { user_id: USER.id, organization_id: ORG.id, token_hash: dead, expires_at: new Date(Date.now() - 3600e3).toISOString() },
  ], "return=minimal");

  // The ISO value carries a 'T'; Postgres' text form of the column carries a
  // space, and ' ' < 'T', so a text comparison would drop the live session.
  const q = (h) => `user_sessions?token_hash=eq.${h}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}` +
    `&select=id,organization_id,expires_at,users(id,email,full_name,locale)&limit=1`;
  const rows = await rest(q(live));
  assert.equal(rows.length, 1);
  const s = rows[0];
  assert.deepEqual(Object.keys(s).sort(), ["expires_at", "id", "organization_id", "users"]);
  assert.equal(s.organization_id, ORG.id);
  assert.match(s.expires_at, isoRe);
  assert.ok(s.users && !Array.isArray(s.users), "to-one embed is an object, not an array");
  assert.deepEqual(s.users, { id: USER.id, email: USER.email, full_name: "Owner", locale: "ar" });

  assert.deepEqual(await rest(q(dead)), [], "expired session excluded");

  // Revoking hides it too (revoked_at=is.null).
  await rest(`user_sessions?token_hash=eq.${live}`, { method: "PATCH", body: { revoked_at: new Date().toISOString() }, prefer: "return=minimal" });
  assert.deepEqual(await rest(q(live)), []);
});

// ------------------------------------------------------------------- TYPES --
it("timestamps come back as ISO strings with T and +00:00, numerics and bigints as numbers", async () => {
  const [org] = await post("organizations", { name_ar: "أنواع" });
  await post("wallet_accounts", { organization_id: org.id }, "return=minimal");
  const [tx] = await post("wallet_transactions", { organization_id: org.id, type: "topup", amount: 150.75 });
  assert.equal(typeof tx.amount, "number", "numeric(12,2) → number, not the pg default string");
  assert.equal(tx.amount, 150.75);
  assert.equal(typeof tx.created_at, "string", "never a Date object");
  assert.match(tx.created_at, isoRe);

  const [doc] = await post("documents", { organization_id: org.id, category: "cr", title: "سجل" });
  const [v] = await post("document_versions", { document_id: doc.id, version_no: 1, storage_key: uniq("k"), size_bytes: 12345678901 });
  assert.equal(v.size_bytes, 12345678901, "bigint → number");
  assert.equal(doc.expiry_date, null);
  await rest(`documents?id=eq.${doc.id}`, { method: "PATCH", body: { expiry_date: "2027-01-31" }, prefer: "return=minimal" });
  const [again] = await rest(`documents?id=eq.${doc.id}&select=expiry_date,created_at`);
  assert.equal(again.expiry_date, "2027-01-31", "date stays a plain YYYY-MM-DD string");
  assert.match(again.created_at, isoRe);
  assert.equal(typeof org.profile_completeness, "number");
});

// ------------------------------------------------------------------ EMBEDS --
it("one-to-many embed: documents with document_versions(...) gives an array per document, [] when none", async () => {
  const [org] = await post("organizations", { name_ar: "مستندات" });
  const [withVersions] = await post("documents", { organization_id: org.id, category: "cr", title: "له نسخ" });
  const [bare] = await post("documents", { organization_id: org.id, category: "gosi", title: "بلا نسخ" });
  await post("document_versions", [
    { document_id: withVersions.id, version_no: 1, storage_key: uniq("v1"), file_name: "a.pdf" },
    { document_id: withVersions.id, version_no: 2, storage_key: uniq("v2"), file_name: "b.pdf" },
  ], "return=minimal");

  const rows = await rest(`documents?organization_id=eq.${org.id}&select=id,category,title,document_versions(id,version_no,file_name,storage_key,uploaded_at)&order=created_at.desc`);
  assert.equal(rows.length, 2);
  assert.equal(rows[0].id, bare.id, "created_at.desc — the later insert first");
  assert.deepEqual(rows[0].document_versions, [], "no versions → empty array, not null");
  const vs = rows[1].document_versions;
  assert.ok(Array.isArray(vs) && vs.length === 2);
  for (const v of vs) {
    assert.deepEqual(Object.keys(v).sort(), ["file_name", "id", "storage_key", "uploaded_at", "version_no"]);
    assert.match(v.uploaded_at, isoRe, "timestamps inside embeds are ISO too (to_json)");
    assert.equal(typeof v.version_no, "number");
  }
});

it("!inner keeps only rows whose related row exists; plain embed yields null for a missing parent", async () => {
  // The repo's storage-key lookup: version → parent document.
  const [org] = await post("organizations", { name_ar: "inner" });
  const [doc] = await post("documents", { organization_id: org.id, category: "cr", title: "t" });
  const key = uniq("key");
  await post("document_versions", { document_id: doc.id, version_no: 1, storage_key: key }, "return=minimal");
  const hit = await rest(`document_versions?storage_key=eq.${key}&select=storage_key,documents!inner(organization_id)&limit=1`);
  assert.deepEqual(hit, [{ storage_key: key, documents: { organization_id: org.id } }]);
  assert.deepEqual(await rest(`document_versions?storage_key=eq.${uniq("missing")}&select=storage_key,documents!inner(organization_id)&limit=1`), []);

  // A parent that is genuinely absent: tasks.request_id is nullable.
  const [req] = await post("requests", { ref: uniq("BP-R"), type: "CONSULTATION", title: "طلب" });
  const [linked] = await post("tasks", { organization_id: org.id, title: "مرتبطة", request_id: req.id });
  const [orphan] = await post("tasks", { organization_id: org.id, title: "يتيمة" });
  const inner = await rest(`tasks?organization_id=eq.${org.id}&select=id,requests!inner(ref,title)&order=created_at`);
  assert.deepEqual(inner, [{ id: linked.id, requests: { ref: req.ref, title: "طلب" } }], "orphan excluded by !inner");
  const left = await rest(`tasks?organization_id=eq.${org.id}&select=id,requests(ref)&order=created_at`);
  assert.deepEqual(left, [{ id: linked.id, requests: { ref: req.ref } }, { id: orphan.id, requests: null }]);

  // Many side of !inner: documents having at least one version.
  const [noVersions] = await post("documents", { organization_id: org.id, category: "id", title: "empty" });
  const docs = await rest(`documents?organization_id=eq.${org.id}&select=id,document_versions!inner(id)`);
  assert.deepEqual(docs.map((d) => d.id), [doc.id]);
  assert.ok(!docs.some((d) => d.id === noVersions.id));
});

it("the other embed shapes the repo issues resolve from real columns (prefix-stripped FK, parent via *_id)", async () => {
  // support_tickets → ticket_messages: the FK is ticket_id, not support_ticket_id.
  const [tk] = await post("support_tickets", { number: uniq("BP-TKT"), organization_id: ORG.id, subject: "مشكلة" });
  await post("ticket_messages", { ticket_id: tk.id, author_kind: "client", body: "مرحباً" }, "return=minimal");
  const [t] = await rest(`support_tickets?id=eq.${tk.id}&select=id,number,subject,ticket_messages(author_kind,body,created_at)`);
  assert.equal(t.ticket_messages.length, 1);
  assert.equal(t.ticket_messages[0].body, "مرحباً");
  assert.match(t.ticket_messages[0].created_at, isoRe);

  // organization_members → organizations (parent through organization_id).
  await post("organization_members", { organization_id: ORG.id, user_id: USER.id, role_id: "owner" }, "return=minimal");
  const m = await rest(`organization_members?user_id=eq.${USER.id}&status=eq.active&select=organization_id,role_id,organizations(id,name_ar,name_en,cr_number)`);
  assert.deepEqual(m, [{ organization_id: ORG.id, role_id: "owner", organizations: { id: ORG.id, name_ar: ORG.name_ar, name_en: "Test Org", cr_number: null } }]);

  // request_events → requests, with a dotted filter value (event=eq.followup.reminded).
  const [req] = await post("requests", { ref: uniq("BP-R"), type: "CONSULTATION", title: "متابعة" });
  await post("request_events", [
    { request_id: req.id, actor_kind: "system", event: "followup.reminded", details: { n: 1 } },
    { request_id: req.id, actor_kind: "system", event: "request.created" },
  ], "return=minimal");
  const ev = await rest(`request_events?request_id=eq.${req.id}&event=eq.followup.reminded&select=event,details,requests(ref,title,status)`);
  assert.deepEqual(ev, [{ event: "followup.reminded", details: { n: 1 }, requests: { ref: req.ref, title: "متابعة", status: "NEW" } }]);
});

// ----------------------------------------------------------------- FILTERS --
it("filters: eq/neq/in/not.in/is.null/not.is.null/gte/like/ilike/or", async () => {
  const [org] = await post("organizations", { name_ar: "مرشّحات" });
  const since = new Date(Date.now() - 60e3).toISOString();
  await post("tasks", [
    { organization_id: org.id, title: "فتح", status: "open", urgency: "urgent", details: "زيارة الرياض", due_at: new Date().toISOString() },
    { organization_id: org.id, title: "جارٍ", status: "in_progress", urgency: "soon", details: "Jeddah trip" },
    { organization_id: org.id, title: "منجزة", status: "done", urgency: "normal", details: "PAYID:ab_1 settled" },
    { organization_id: org.id, title: "ملغاة", status: "cancelled", urgency: "normal", details: "PAYID:abX1 other" },
  ], "return=minimal");
  const titles = async (q) => (await rest(`tasks?organization_id=eq.${org.id}&${q}&select=title&order=title`)).map((r) => r.title).sort();

  assert.deepEqual(await titles("status=eq.open"), ["فتح"]);
  assert.deepEqual(await titles("status=neq.open"), ["جارٍ", "ملغاة", "منجزة"]);
  assert.deepEqual(await titles("status=in.(open,in_progress,blocked)"), ["جارٍ", "فتح"]);
  assert.deepEqual(await titles('status=in.("open",done)'), ["فتح", "منجزة"], "quoted list values accepted");
  assert.deepEqual(await titles("status=not.in.(done,cancelled)"), ["جارٍ", "فتح"]);
  assert.deepEqual(await titles("status=in.()"), [], "empty list matches nothing");
  assert.deepEqual(await titles("due_at=is.null"), ["جارٍ", "ملغاة", "منجزة"]);
  assert.deepEqual(await titles("due_at=not.is.null"), ["فتح"]);
  assert.deepEqual(await titles("human_action=eq.false&urgency=in.(urgent,soon)"), ["جارٍ", "فتح"]);
  assert.deepEqual(await titles("human_action=is.false&urgency=eq.urgent"), ["فتح"]);
  assert.equal((await titles(`created_at=gte.${encodeURIComponent(since)}`)).length, 4, "gte on timestamptz with an ISO 'T' value");
  assert.deepEqual(await titles(`created_at=gte.${encodeURIComponent(new Date(Date.now() + 864e5).toISOString())}`), []);
  assert.deepEqual(await titles(`created_at=lt.${encodeURIComponent(since)}`), []);

  // Wildcards: * → %; a literal _ in the value must NOT act as a wildcard.
  assert.deepEqual(await titles("details=ilike.*رياض*"), ["فتح"]);
  assert.deepEqual(await titles("details=like.*jeddah*"), [], "like is case-sensitive");
  assert.deepEqual(await titles("details=ilike.*jeddah*"), ["جارٍ"]);
  assert.deepEqual(await titles("details=like.*PAYID:ab_1*"), ["منجزة"], "underscore escaped, so abX1 is not matched");
  assert.deepEqual(await titles("details=not.ilike.*PAYID*"), ["جارٍ", "فتح"]);

  // or=(…) as api/_simple.js builds it, with ilike parts and with eq parts.
  assert.deepEqual(await titles(`or=(title.ilike.*فتح*,details.ilike.*jeddah*)`), ["جارٍ", "فتح"]);
  assert.deepEqual(await titles(`or=(status.eq.done,status.eq.cancelled)&urgency=eq.normal`), ["ملغاة", "منجزة"], "or is AND-ed with sibling filters");
  assert.deepEqual(await titles(`or=(status.in.(open),due_at.is.null)`), ["جارٍ", "فتح", "ملغاة", "منجزة"], "nested parentheses inside or");
});

// ------------------------------------------------------------------- ORDER --
it("order/limit/offset, and NULL placement follows Postgres defaults unless nullslast/nullsfirst", async () => {
  const [org] = await post("organizations", { name_ar: "ترتيب" });
  const day = (n) => new Date(Date.UTC(2026, 0, n)).toISOString();
  // Separate POSTs so created_at differs (one statement → one now()).
  const [a] = await post("tasks", { organization_id: org.id, title: "a", due_at: day(3) });
  const [b] = await post("tasks", { organization_id: org.id, title: "b" });
  const [c] = await post("tasks", { organization_id: org.id, title: "c", due_at: day(1) });
  const ids = async (q) => (await rest(`tasks?organization_id=eq.${org.id}&${q}&select=id`)).map((r) => r.id);

  assert.deepEqual(await ids("order=created_at.desc"), [c.id, b.id, a.id]);
  assert.deepEqual(await ids("order=created_at"), [a.id, b.id, c.id], "bare column = asc");
  assert.deepEqual(await ids("order=created_at.asc&limit=2"), [a.id, b.id]);
  assert.deepEqual(await ids("order=created_at.asc&limit=2&offset=1"), [b.id, c.id]);
  assert.deepEqual(await ids("order=title.desc"), [c.id, b.id, a.id], "text ordering");
  assert.deepEqual(await ids("order=due_at"), [c.id, a.id, b.id], "asc → nulls last");
  assert.deepEqual(await ids("order=due_at.desc"), [b.id, a.id, c.id], "desc → nulls first (Postgres/PostgREST default)");
  assert.deepEqual(await ids("order=due_at.desc.nullslast"), [a.id, c.id, b.id]);
  assert.deepEqual(await ids("order=due_at.asc.nullsfirst"), [b.id, c.id, a.id]);
  assert.deepEqual(await ids("order=due_at.desc.nullslast,created_at.asc"), [a.id, c.id, b.id], "two keys");
});

// ------------------------------------------------------------------ UPSERT --
it("upsert: merge-duplicates updates in place; ignore-duplicates neither duplicates nor returns", async () => {
  const email = uniq("dup") + "@test.local";
  const [first] = await post("users?on_conflict=email", { email, full_name: "قبل" }, "resolution=merge-duplicates,return=representation");
  const [second] = await post("users?on_conflict=email", { email, full_name: "بعد", locale: "en" }, "resolution=merge-duplicates,return=representation");
  assert.equal(second.id, first.id, "same row, not a new one");
  assert.equal(second.full_name, "بعد");
  assert.equal(second.locale, "en");
  assert.equal((await rest(`users?email=eq.${encodeURIComponent(email)}&select=id`)).length, 1);
  assert.equal(await post("users?on_conflict=email", { email, full_name: "صامت" }, "resolution=merge-duplicates,return=minimal"), null);

  const key = uniq("idem");
  const n = { organization_id: ORG.id, event: "order_created", title: "طلب", idempotency_key: key };
  assert.equal(await post("notifications?on_conflict=idempotency_key", n, "resolution=ignore-duplicates,return=minimal"), null);
  assert.equal(await post("notifications?on_conflict=idempotency_key", { ...n, title: "مكرر" }, "resolution=ignore-duplicates,return=minimal"), null);
  const rows = await rest(`notifications?idempotency_key=eq.${key}&select=title`);
  assert.deepEqual(rows, [{ title: "طلب" }], "first write wins, no duplicate");
});

// ------------------------------------------------------------ PATCH/DELETE --
it("PATCH and DELETE with filters return the affected rows, or null under return=minimal", async () => {
  const [org] = await post("organizations", { name_ar: "تعديل" });
  await post("tasks", [
    { organization_id: org.id, title: "x", status: "open" },
    { organization_id: org.id, title: "y", status: "open" },
    { organization_id: org.id, title: "z", status: "done" },
  ], "return=minimal");

  const patched = await rest(`tasks?organization_id=eq.${org.id}&status=eq.open`, { method: "PATCH", body: { status: "blocked", assigned_to: "bp" } });
  assert.deepEqual(patched.map((r) => [r.title, r.status, r.assigned_to]).sort(), [["x", "blocked", "bp"], ["y", "blocked", "bp"]]);
  assert.equal(await rest(`tasks?organization_id=eq.${org.id}&title=eq.z`, { method: "PATCH", body: { status: "cancelled" }, prefer: "return=minimal" }), null);
  assert.deepEqual(await rest(`tasks?organization_id=eq.${org.id}&title=eq.z&select=status`), [{ status: "cancelled" }]);
  assert.deepEqual(await rest(`tasks?organization_id=eq.${org.id}`, { method: "PATCH", body: {} }), [], "empty patch touches nothing");

  const deleted = await rest(`tasks?organization_id=eq.${org.id}&status=eq.blocked`, { method: "DELETE" });
  assert.deepEqual(deleted.map((r) => r.title).sort(), ["x", "y"]);
  assert.deepEqual((await rest(`tasks?organization_id=eq.${org.id}&select=title`)).map((r) => r.title), ["z"]);
  assert.equal(await rest(`tasks?organization_id=eq.${org.id}`, { method: "DELETE", prefer: "return=minimal" }), null);
  assert.deepEqual(await rest(`tasks?organization_id=eq.${org.id}`), []);
});

// -------------------------------------------------------------- JSON/ARRAY --
it("jsonb and text[] round-trip through POST, GET and PATCH", async () => {
  const conversation = [{ role: "user", content: "أريد تأسيس شركة", at: "2026-09-01T10:00:00Z" }, { role: "assistant", content: "أهلاً", at: "2026-09-01T10:00:05Z" }];
  const quote = { number: "Q-1", status: "sent", items: [{ code: "BP-CF-01", qty: 1, price: 1500 }], net: 1500, vat: 225, total: 1725, notes: null };
  const [req] = await post("requests", { ref: uniq("BP-R"), type: "COMPANY_FORMATION", title: "تأسيس", conversation, quote, attachments: [] });
  assert.deepEqual(req.conversation, conversation);
  assert.deepEqual(req.quote, quote);
  assert.deepEqual(req.scope, [], "jsonb default applied");
  const [got] = await rest(`requests?ref=eq.${req.ref}&select=ref,title,status,quote,conversation&limit=1`);
  assert.deepEqual(got.quote, quote);
  assert.deepEqual(got.conversation, conversation);
  const [patched] = await rest(`requests?id=eq.${req.id}`, { method: "PATCH", body: { quote: { ...quote, status: "approved" }, scope: [{ code: "BP-CF-01", title: "تأسيس", qty: 1 }] } });
  assert.equal(patched.quote.status, "approved");
  assert.deepEqual(patched.scope, [{ code: "BP-CF-01", title: "تأسيس", qty: 1 }]);
  // A jsonb column set to a bare string must stay a JSON string, not become NULL/invalid.
  const [asText] = await rest(`requests?id=eq.${req.id}`, { method: "PATCH", body: { payment: "pending" } });
  assert.equal(asText.payment, "pending");

  const [org] = await post("organizations", { name_ar: "قطاعات" });
  const sectors = ["Construction", "Retail & Wholesale", "تقنية"];
  const [bp] = await post("bd_profiles?on_conflict=organization_id", { organization_id: org.id, target_sectors: sectors, target_cities: ["Riyadh"], extracted: { cr: "1010" } }, "resolution=merge-duplicates,return=representation");
  assert.deepEqual(bp.target_sectors, sectors, "text[] returned as a JS array");
  assert.deepEqual(bp.target_cities, ["Riyadh"]);
  assert.deepEqual(bp.extracted, { cr: "1010" });
  const [read] = await rest(`bd_profiles?organization_id=eq.${org.id}&select=target_sectors,target_cities&limit=1`);
  assert.deepEqual(read, { target_sectors: sectors, target_cities: ["Riyadh"] });
  const [upd] = await rest(`bd_profiles?organization_id=eq.${org.id}`, { method: "PATCH", body: { target_cities: [] } });
  assert.deepEqual(upd.target_cities, []);
  assert.deepEqual(upd.target_sectors, sectors, "untouched array column keeps its value");
});

// ------------------------------------------------------------------ SAFETY --
it("anything outside the grammar rejects loudly — never a silent full-table read", async () => {
  await assert.rejects(rest("tasks?status=foo.x"), /غير مدعوم/, "unknown operator");
  await assert.rejects(rest("tasks?status=open"), /غير مفهوم/, "filter without an operator");
  await assert.rejects(rest("tasks?status=is.maybe"), /غير مدعوم/, "is.<not null/true/false>");
  await assert.rejects(rest("users?select=id;drop"), /معرّف غير صالح/, "identifier with punctuation");
  // Values are parameters, never text: SQL inside a value is just an email
  // nobody has, so the query answers [] and the table is still there.
  assert.deepEqual(await rest(`users?select=id&email=eq.${encodeURIComponent('x"; drop table users;--')}`), []);
  await assert.rejects(rest("users?order=created_at desc"), /معرّف غير صالح/, "identifier in order");
  await assert.rejects(rest("nope_table?select=*"), (e) => /nope_table/.test(e.message), "unknown table");
  await assert.rejects(rest("tasks?select=id,nope(id)"), /غير موجود/, "unknown embed table");
  await assert.rejects(rest("tasks?or=(garbage)"), /or غير مفهوم/, "or with no column.op");
  await assert.rejects(rest("tasks?or=(status.bogus.x)"), /غير مدعوم/, "or part with an unknown operator");
  await assert.rejects(rest("tasks", { method: "PUT" }), /طريقة غير مدعومة/);
  await assert.rejects(post("tasks", [{}]), /بلا أعمدة/, "row with no columns");
  await assert.rejects(post("tasks", { organization_id: ORG.id, title: "t", nope: 1 }), (e) => /nope/.test(e.message), "unknown column on insert");
  // Sanity: the guard above ran against a table that does have rows.
  assert.ok((await rest("users?select=id&limit=1")).length === 1);
});

// -------------------------------------------------------------------- MISC --
it("azpgPing reports ok when configured", async () => {
  assert.deepEqual(await azpg.azpgPing(), { ok: true });
  assert.equal(azpg.azurePgReady(), true);
});

test("pgTextToIso normalises Postgres text timestamps to PostgREST's ISO form", async () => {
  // Pure function: runs even without a database.
  const { pgTextToIso } = await import(`../api/_azpg.js?t=${Date.now()}-unit`);
  assert.equal(pgTextToIso("2026-09-01 22:44:16.582+00"), "2026-09-01T22:44:16.582+00:00");
  assert.equal(pgTextToIso("2026-09-01 22:44:16+00"), "2026-09-01T22:44:16+00:00");
  assert.equal(pgTextToIso("2026-09-01 22:44:16.5+03:30"), "2026-09-01T22:44:16.5+03:30");
  assert.equal(pgTextToIso("2026-09-01 22:44:16"), "2026-09-01T22:44:16", "timestamp without time zone keeps no offset");
  assert.equal(pgTextToIso("2026-09-01"), "2026-09-01", "a date passes through");
  assert.equal(pgTextToIso("infinity"), "infinity", "unparseable text passes through untouched");
  assert.equal(pgTextToIso(null), null);
  assert.equal(pgTextToIso(undefined), undefined);
});

it("views answer GET like tables: wallet_balances derives the ledger sum", async () => {
  const [org] = await post("organizations", { name_ar: "محفظة" });
  assert.deepEqual(await rest(`wallet_balances?organization_id=eq.${org.id}&select=balance`), [], "no ledger rows → no balance row");
  await post("wallet_accounts?on_conflict=organization_id", { organization_id: org.id }, "resolution=ignore-duplicates,return=minimal");
  await post("wallet_transactions", [
    { organization_id: org.id, type: "topup", amount: 100 },
    { organization_id: org.id, type: "payment", amount: -25.5, note: `PAYID:${uniq("p")}` },
  ], "return=minimal");
  assert.deepEqual(await rest(`wallet_balances?organization_id=eq.${org.id}&select=balance`), [{ balance: 74.5 }]);
  const all = await rest("wallet_balances?select=*&order=balance.desc");
  assert.ok(all.some((r) => r.organization_id === org.id && r.balance === 74.5));
  const amounts = (await rest(`wallet_transactions?organization_id=eq.${org.id}&select=amount`)).map((r) => r.amount);
  assert.equal(amounts.reduce((a, b) => a + b, 0), 74.5, "callers sum amounts as numbers");
});
